version: '3.8'

services:
  synthesis-mcp:
    build: .
    container_name: synthesis-mcp
    environment:
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_PORT=${EMAIL_PORT:-143}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL:-false}
      - STUDY_GOAL_MINUTES=${STUDY_GOAL_MINUTES:-300}
      - MINIMUM_STUDY_MINUTES=${MINIMUM_STUDY_MINUTES:-20}
    volumes:
      - ./synthesis-server.py:/app/synthesis-server.py:ro
      - ./.env:/app/.env:ro
    command: ["python3", "/app/synthesis-server.py"]
    restart: unless-stopped

  synthesis-mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: synthesis-mcpo
    ports:
      - "${MCPO_PORT:-8002}:8000"
    volumes:
      - ./synthesis-server.py:/app/synthesis-server.py:ro
      - ./.env:/app/.env:ro
      - ./mcpo-config.json:/app/mcpo-config.json:ro
    command: 
      - "mcpo"
      - "--config"
      - "/app/mcpo-config.json"
      - "--host"
      - "0.0.0.0"
      - "--port" 
      - "8000"
      - "--api-key"
      - "${MCPO_API_KEY:-synthesis-mcpo-key-2024}"
    environment:
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_PORT=${EMAIL_PORT:-143}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL:-false}
      - STUDY_GOAL_MINUTES=${STUDY_GOAL_MINUTES:-300}
      - MINIMUM_STUDY_MINUTES=${MINIMUM_STUDY_MINUTES:-20}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/openapi.json"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: synthesis-network